swagger: '2.0'
info:
  title: Intelligent Transport System 3.4 Open API Interface
  version: "3.4"
  description: |
    # Overview
    This document describes the functions and Message Format of the quicktron **Intelligent Transport System 3.0** the standard interface provided by the system. 
    # Purpose
    For quicktron technicians, upstream developers, project consultants, etc. to do interface requirements specification reference use, to call the quicktron system 3.0 open API interface docking system for system development and maintenance use. 
    # Target Audience
    Technical staff, project consultant, Host interface developer. 
  license:
    name: Apache 2.0
host: "10.203.207.88:9003"
schemes:
  - http
paths:
  /api/quicktron/rss/warehouse/{warehouseId}/transport-order/carrier/submit:
    post:
      tags:
        - Horizontal Transport
      summary: Horizontal Rack Transport Interface
      description: Horizontal Transport Job distribution, batch Job distribution is supported.
      parameters:
        - name: warehouseId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                upstreamOrderNo:
                  type: string
                  description: Upstream system job number, globally Unique
                jobPriority:
                  type: integer
                  description: Priority of Job execution
                letDownFlag:
                  type: integer
                  description: Indication on the jobtype 1:online Job, AGV will bring the rack to the destination without putting the rack down 2:offline Job, AGV puts down the rack when arriving at the destination
                startMapCode:
                  type: string
                  description: Starting Map Code, required when multiple maps are active
                rackCode:
                  type: string
                  description: Rack No.
                startPoint:
                  type: string
                  description: Start Point encoding
                startPointName:
                  type: string
                  description: Start Point short code
                startArea:
                  type: string
                  description: Starting Area
                targetMapCode:
                  type: string
                  description: Target Map Code, required when multiple maps are active
                targetPoint:
                  type: string
                  description: Target Point encoding
                targetPointName:
                  type: string
                  description: Short code of target point
                targetArea:
                  type: string
                  description: Target Area
                awaitArea:
                  type: string
                  description: Waiting for Area
                rackTypeCode:
                  type: string
                  description: Shelf Type encoding
                robotType:
                  type: string
                  description: Specify Robot Type
                robotCode:
                  type: string
                  description: Robot Code, specifying the robot execution Job
                deadline:
                  type: string
                  description: Job execution is required to be completed before the deadline, in the format of yyyy-MM-dd HH:mm:ss
                workHeading:
                  type: string
                  description: Rack job angle, 0, 90, 180, -90
                needOperation:
                  type: boolean
                  description: Do you need practical operation? If you don't fill it in, you won't do practical operation by default.
                needReset:
                  type: boolean
                  description: Whether Return to Warehouse is required. If it is not filled in, it is not required by default.
              required:
                - upstreamOrderNo
                - jobPriority
                - letDownFlag
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
        '201':
          description: Created  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/quicktron/jobreport:
    post:
      tags:
        - Horizontal Transport
      summary: Horizontal Job Completion Report Interface
      description: Transport Job Order Status reporting.
        
        URL should be defined by Host system 
        
        By default the Job statusses are by default one of the following
        
          - qs
          
          - sq
        
      parameters:
        - name: body
          in: body
          required: true
          description: JSON Body 
          schema:
            type: object
            properties:
              upstreamOrderNo:
                type: string
                description: Upstream System job number
              state:
                type: string
                description: Current job status
              orderType:
                type: string
                description: Job Order Type
              rackCode:
                type: string
                description: Shelf Code
              robotCode:
                type: string
                description: Robot code of the assigned robot
              workHeading:
                type: string
                description: Rack job target angle
              startPoint:
                type: string
                description: Start point encoding
              startPointName:
                type: string
                description: Start point name
              startArea:
                type: string
                description: Start area encoding
              targetPoint:
                type: string
                description: Target point encoding
              targetPointName:
                type: string
                description: Target point name
              targetArea:
                type: string
                description: Target area encoding
              startMapCode:
                type: string
                description: Start map code
              targetMapCode:
                type: string
                description: Target map code
              
              
              
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        