swagger: '2.0'
info:
  title: Intelligent Transport System 3.4 Open API Interface
  version: "3.4"
  description: |
    # Overview
    This document describes the functions and Message Format of the quicktron **Intelligent Transport System 3.0** the standard interface provided by the system. 
    # Purpose
    For quicktron technicians, upstream developers, project consultants, etc. to do interface requirements specification reference use, to call the quicktron system 3.0 open API interface docking system for system development and maintenance use. 
    # Target Audience
    Technical staff, project consultant, Host interface developer. 
  license:
    name: Apache 2.0
host: "10.203.207.87:9003"
schemes:
  - http
paths:
  /api/quicktron/rss/warehouse/{warehouseId}/transport-order/carrier/submit:
    post:
      tags:
        - Common interfaces
      summary: Horizontal Rack Transport Interface
      description: Horizontal Transport Job distribution, batch Job distribution is supported.
      parameters:
        - name: warehouseId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                upstreamOrderNo:
                  type: string
                  description: Upstream system job number, globally Unique
                jobPriority:
                  type: integer
                  description: Priority of Job execution
                  default: 1
                letDownFlag:
                  type: integer
                  description: Indication on the jobtype 1:online Job, AGV will bring the rack to the destination without putting the rack down 2:offline Job, AGV puts down the rack when arriving at the destination
                  default: 1
                startMapCode:
                  type: string
                  description: Starting Map Code, required when multiple maps are active
                rackCode:
                  type: string
                  description: Rack No., at least 1 start is required
                startPoint:
                  type: string
                  description: Start Point encoding, at least 1 start is required
                startPointName:
                  type: string
                  description: Start Point short code, at least 1 start is required
                startArea:
                  type: string
                  description: Starting Area
                targetMapCode:
                  type: string
                  description: Target Map Code, required when multiple maps are active
                targetPoint:
                  type: string
                  description: Target Point encoding, at least 1 target is required
                targetPointName:
                  type: string
                  description: Short code of target point, at least 1 target is required
                targetArea:
                  type: string
                  description: Target Area, at least 1 target is required
                awaitArea:
                  type: string
                  description: Waiting for Area
                rackTypeCode:
                  type: string
                  description: Shelf Type encoding
                robotType:
                  type: string
                  description: Specify Robot Type
                robotCode:
                  type: string
                  description: Robot Code, specifying the robot execution Job
                deadline:
                  type: string
                  description: Job execution is required to be completed before the deadline, in the format of yyyy-MM-dd HH:mm:ss
                workHeading:
                  type: string
                  description: Rack job angle, 0, 90, 180, -90
                needOperation:
                  type: boolean
                  description: Do you need practical operation? If you don't fill it in, you won't do practical operation by default.
                needReset:
                  type: boolean
                  description: Whether Return to Warehouse is required. If it is not filled in, it is not required by default.
                lockTime:
                  type: integer
                  description: Robot lock time
                needOut:
                  type: integer 
                  description: Is rack out site after transport (0 - not out of site, 1 - out of site)
              required:
                - upstreamOrderNo
                - jobPriority
                - letDownFlag
                - rackTypeCode
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
        '201':
          description: Created  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/quicktron/rss/warehouse/{warehouseId}/transport-order/carrier/group/submit:
    post:
      tags:
        - Common interfaces
      summary: Job Single Group Delivery Interface
      description: Job single group delivery interface, Batch work order distribution is supported in the work order group.
      parameters:
        - name: warehouseId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                upstreamOrderGroup:
                  type: string
                  description: Upstream system job group
                upstreamOrderNo:
                  type: string
                  description: Upstream system job number, globally Unique
                priority:
                  type: integer
                  description: Priority of Job execution
                  default: 1
                orderGroupMode:
                  type: string
                  description: Specify the execution mode for job single groups (SINGLE - assign the same car to execute the job order in sequence, MULTIPLE - assign multiple cars to execute the job in sequence)
                letDownFlag:
                  type: integer
                  description: Indication on the jobtype 1:online Job, AGV will bring the rack to the destination without putting the rack down 2:offline Job, AGV puts down the rack when arriving at the destination
                  default: 1
                sequence:
                  type: integer
                  description: Job group serial number
                startMapCode:
                  type: string
                  description: Starting Map Code, required when multiple maps are active
                rackCode:
                  type: string
                  description: Rack No., at least 1 start is required
                startPoint:
                  type: string
                  description: Start Point encoding, at least 1 start is required
                startPointName:
                  type: string
                  description: Start Point short code, at least 1 start is required
                startArea:
                  type: string
                  description: Starting Area
                targetMapCode:
                  type: string
                  description: Target Map Code, required when multiple maps are active
                targetPoint:
                  type: string
                  description: Target Point encoding, at least 1 target is required
                targetPointName:
                  type: string
                  description: Short code of target point, at least 1 target is required
                targetArea:
                  type: string
                  description: Target Area, at least 1 target is required
                awaitArea:
                  type: string
                  description: Waiting for Area
                rackTypeCode:
                  type: string
                  description: Shelf Type encoding
                robotType:
                  type: string
                  description: Specify Robot Type
                robotCode:
                  type: string
                  description: Robot Code, specifying the robot execution Job
                workHeading:
                  type: string
                  description: Rack job angle, 0, 90, 180, -90
                needOperation:
                  type: boolean
                  description: Do you need practical operation? If you don't fill it in, you won't do practical operation by default.
                lockTime:
                  type: integer
                  description: Robot lock time
                needOut:
                  type: integer 
                  description: Is rack out site after transport (0 - not out of site, 1 - out of site)
              required:
                - upstreamOrderNo
                - jobPriority
                - letDownFlag
                - rackTypeCode
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
        '201':
          description: Created  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/quicktron/rss/warehouse/{warehouseId}/transport-order/carrier/robotMove:
    post:
      tags:
        - Common interfaces
      summary: Robot Move Job Order Issue Interface
      description: Robot Move Job Order Issue Interface, batch robot Move job order distribution is supported
      parameters:
        - name: warehouseId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                upstreamOrderNo:
                  type: string
                  description: Upstream system job number, globally Unique
                jobPriority:
                  type: integer
                  description: Priority of Job execution
                  default: 1
                targetPoint:
                  type: string
                  description: Target Point encoding, at least 1 target is required
                targetPointName:
                  type: string
                  description: Short code of target point, at least 1 target is required
                targetArea:
                  type: string
                  description: Target Area, at least 1 target is required
                startMapCode:
                  type: string
                  description: Starting Map Code, required when multiple maps are active
                targetMapCode:
                  type: string
                  description: Target Map Code, required when multiple maps are active
                robotType:
                  type: string
                  description: Specify Robot Type
                robotCode:
                  type: string
                  description: Robot Code, specifying the robot execution Job
                deadline:
                  type: string
                  description: Job execution is required to be completed before the deadline, in the format of yyyy-MM-dd HH:mm:ss
                lockTime:
                  type: integer
                  description: Robot lock time
              required:
                - upstreamOrderNo
                - jobPriority
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
        '201':
          description: Created  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/quicktron/rss/warehouse/{warehouseId}/transport-order/carrier/cancel:
    post:
      tags:
        - Common interfaces
      summary: Robot Move Job Order Issue Interface
      description: Robot Move Job Order Issue Interface, batch robot Move job order distribution is supported
      parameters:
        - name: warehouseId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                upstreamOrderNo:
                  type: string
                  description: Upstream system job number, globally Unique
                executeMode:
                  type: string
                  description: Executing mode - RETURN_WAREHOUSE, CURRENT_POINT_LIFT_UP, CURRENT_POINT_PUT_DOWN, TARGET_POINT_PUT_DOWN
                putDownCode:
                  type: string
                  description: Select the drop point encoding
                mapCode:
                  type: string
                  description: Map code
              required:
                - upstreamOrderNo
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
        '201':
          description: Created  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/quicktron/rss/warehouse/{warehouseId}/transport-order/carrier/operationNotice:
    post:
      tags:
        - Common interfaces
      summary: Practical Operation Work Sheet
      description: Call the interface after the Workstation Job operation is completed. If Rack have other Job to perform other Job. Online Workstation Rack directly return to the warehouse, offline Workstation allocation robot return to the warehouse
      parameters:
        - name: warehouseId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                upstreamOrderNo:
                  type: string
                  description: Upstream system job number, globally Unique
                rackCode:
                  type: string
                  description: Rack number
              required:
                - upstreamOrderNo
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
        '201':
          description: Created  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found